
CREATE TABLE IF NOT EXISTS `products`(
`ID` int(11) DEFAULT NOT NULL AUTO_INCREMENT,
`PRODUCT` varchar(500) DEFAULT NULL,
`PRICE` int(11) DEFAULT NULL,
`BRAND` varchar(100) DEFAULT NULL,
`SHOP` varchar(100) DEFAULT NULL,
`IMAGE` varchar(500) DEFAULT NULL,
`TIMESTAMP` int(11) DEAFAULT NULL
PRIMARY KEY(`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
